### ISSUE TITLE
Build task for SCP CF deployment

### ISSUE THREAD

**Issue by gregorwolf** [mikezaschka/cds-dbm#1]
Hi @mikezaschka,

I've tried my first steps to use cds-dbm and run it as a [Tasks](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/a1c184c585f24c1c8dfaf4d1fcc2fde7.html) during MTA deployment. For that I've added a folder [db-deployer](https://github.com/gregorwolf/pg-beershop/tree/master/db-deployer) to my [pg-beershop](https://github.com/gregorwolf/pg-beershop). In the package.json I've defined your Git repository as the source for the npm package and tried the installation. Unfortunately that fails:

```
db-deployer$ npm i

npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /home/gwolf/projects/pg-beershop/db-deployer/node_modules/cds-dbm/dist/cli.js
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/home/gwolf/projects/pg-beershop/db-deployer/node_modules/cds-dbm/dist/cli.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
```

Let me know if the intended use is different.

Best regards
Gregor

**Comment by mikezaschka** [comment]
Hey @gregorwolf ,

thanks for volunteering to use the `cds-dbm`. 👍 
Sadly, it's not yet usable, since I need to add or generate the transpiled Javascript code (the missing _dist_) folder. 
I am going to do some more testing on my side today and will hopefully be able to ship the dist folder (and the npm package) tomorrow. 

Kind regards
Mike

**Comment by mikezaschka** [comment]
Hey @gregorwolf ,

you might start give it a try.
Beware, it's still in the early stages (as is cds-pg), but the tests pass and I have been playing around with a simple project setup to test things manually.

Also important: right now all commands need to be executed via `npx` (e.g. `npx cds-dbm deploy`.

**Comment by gregorwolf** [comment]
Link to the SAP Community discussion: [Can I inject data into a Docker Container deployed via an MTA / Combined Java-Node.JS Buldback?](https://answers.sap.com/questions/13184099/can-i-inject-data-into-a-docker-container-deployed.html) where I've continued the thoughts. Current state is reflected in the [README.md](https://github.com/gregorwolf/pg-beershop/tree/master/db-deployer) of the pg-beershop.

**Comment by gregorwolf** [comment]
A discussed yesterday I’ve created now a deployer that combines the Node.JS and Java buildpack. Check out [db-deployer-java](https://github.com/gregorwolf/pg-beershop/tree/master/db-deployer-java). The deploy script does only the bare minimum: [deploy.sh](https://github.com/gregorwolf/pg-beershop/blob/master/db-deployer-java/src/main/resources/deploy.sh) also the [package.json](https://github.com/gregorwolf/pg-beershop/blob/master/db-deployer-java/src/main/resources/package.json) contains only the bare minimum.

What we still have to solve is that the Java Buildpack expects a jar file as an input. Basically the jar is a ZIP file. But it seems that [creating this jar only with the files that we need](https://github.com/gregorwolf/pg-beershop/blob/master/package.json#L17) does not work. So for the moment we have to live with the fact to run a maven build that includes the files that we need an then deploy to SAP CP Cloud Foundry.

**Comment by mikezaschka** [comment]
Hey @gregorwolf,
I did some investigation. Maybe it's possible to use the multi buildpacks, but skip the Java one in favor of the apt buildback (https://github.com/cloudfoundry/apt-buildpack).
This one allows the Node.js buildpack to be last and thus support `npm..` and it enables the installation of java via apt-packages. The only thing left should be adding java to the PATH:

- https://stackoverflow.com/a/49214154
- https://stackoverflow.com/questions/63927417/cloudfoundry-and-jdk

Sounds promising.

**Comment by gregorwolf** [comment]
Hi @mikezaschka,

this approach is now implemented in [pg-beershop/db-deployer-apt](https://github.com/gregorwolf/pg-beershop/tree/master/db-deployer-apt). And after your adjustments in cds-dbm the deploy to the SAP CP PostgreSQL Hyperscaler service is working. Do you want to continue here regarding the implementation that replaces the manual copy that I've implemented in [mta.yaml#L18](https://github.com/gregorwolf/pg-beershop/blob/master/mta.yaml#L18)?

**Comment by mikezaschka** [comment]
I deployed version 0.0.14, which contains the fixes in the feature/scp branch, so you can switch back to the npm package.
Next thing will be the `build` task. Let's keep this open and to discuss this further.

**Comment by mikezaschka** [comment]
Almost there:

package.json (could be also in .cdsrc)
![image](https://user-images.githubusercontent.com/9880/100059593-9d274500-2e2b-11eb-9fed-a370339fd139.png)

`cds-dbm build` task, a full wrapper around `cds build` (which will not work in the project, because it does not know postgres-cf)
![image](https://user-images.githubusercontent.com/9880/100059229-0195d480-2e2b-11eb-8b07-c3cbff799164.png)

Will do some fine tuning on Thursday and then push things.
Sadly `@sap/cds` really is locking things up, so I had to overwrite some internals to make it work with the default build mechanism.

**Comment by gregorwolf** [comment]
Hi @mikezaschka,

I've switched to:

```   
    "cds-dbm": "^0.0.14",
    "cds-pg": "^0.0.30",
```

in the [pg-beershop deployer](https://github.com/gregorwolf/pg-beershop/tree/master/db-deployer-apt). But the deploy fails with:

```   
Unexpected error running Liquibase: Migration failed for change set tmp/_autodeploy.json::1606294293009-1::vcap (generated):
     Reason: liquibase.exception.DatabaseException: ERROR: must be owner of view pg_stat_statements [Failed SQL: (0) DROP VIEW public.pg_stat_statements]
```   

What version should I currently use?

Best regards
Gregor

**Comment by mikezaschka** [comment]
If this still is an issue, then please switch back to the feature/scp branch. I may have missed something in version 0.0.14.
I am going to work on `cds-dbm` tomorrow and add some tests to really make sure, those statements get removed in the next version.

**Comment by mikezaschka** [comment]
So, with version 0.0.17 (and up), you should be ready to go:

Add this to the .cdsrc file or in the package json:

```json
    "build": {
      "tasks": [
        {
          "use": "node-cf",
          "src": "srv"
        },
        {
          "use": "postgres-cf",
          "src": "db"
        }
      ]
    },
```

Use this in the mta.yml file:

```yaml
build-parameters:
  before-all:
    - builder: custom
      commands:
        - npm install --production
        - npx cds-dbm build --production

```

**Comment by gregorwolf** [comment]
Works like charm now. I've updated the pg-beershop. Would using:

```
npx cds-dbm build
```

without the --production parameter mean that you also include the express app that I've included in the prototype? That would help to get the module started to ssh into it.

**Comment by mikezaschka** [comment]
The postgres-cf deployment task will do the following steps:

* generate the csn.json
* create the package.json from a template
* create the deploy.sh from a template and add the executeCmd (default is `npx cds-dbm deploy --load-via delta`), which can be overwritten in the task options like this:
```json
 "build": {
    "tasks": [
        {
            "use": "node-cf",
            "src": "srv"
        },
        {
            "use": "postgres-cf",
            "src": "db",
            "options": {
                "deployCmd": "npx cds-dbm deploy --load-via delta --auto-undeploy"
            }
        }
    ]
},
```
* create the manifest.yml from a template (haven't tested this yet)
* create the apt.yml from a template
* copy undeploy.json file (if one is available)
* move the .csv files into the data folder
* **copy any other folder/file than .cds and .csv from the original db folder**

So if you want your server to be deployed as well, just put the files into the original _db_ folder.

**Comment by gregorwolf** [comment]
I would suggest `startCmd`. When that option is set, then the package.json should get a scripts section with the specified start. The expess implementation can be put in the source db folder as a copy from there is already done.

**Comment by mikezaschka** [comment]
[Pushed into main](https://github.com/mikezaschka/cds-dbm/commit/ba3866c6d7c254f01f923b223fcbc1c33670f18a#diff-75cb37c1ecc50055fcd3a28aea2f78f70ee79e4fa7f9af8f46a1d57afeffd0adR115) 

Will release this over the weekend.

**Comment by mikezaschka** [comment]
Version 0.0.18 has been release. 
A blog post describing the whole build and deploy process is in review by SAP.

Closing this one.
