### ISSUE TITLE
release 0.0.30 does not contain latest changes

### ISSUE THREAD

**Issue by F7502** [mikezaschka/cds-dbm#156]
Many thanks for the quick response on https://github.com/mikezaschka/cds-dbm/pull/155 and the subsequent release. I installed and tested it but the `dialect` field is still missing in the `package.json` generated during a build. I checked the downloaded files in my `node_modules` folder and there the template for `package.json` is still the old version without the `dialect` field. Could you check if there went anything wrong with this release? Thanks in advance :-)

**Comment by mikezaschka** [comment]
Hi @F7502, 
I released another version and the `dialect` parameter should now be available in the generated package.json. 
Kind regards,
Mike

**Comment by F7502** [comment]
Thanks, can confirm that it works now.
