### ISSUE TITLE
Deploy error - clues on how to resolve

### ISSUE THREAD

**Issue by sedacrivity** [mikezaschka/cds-dbm#179]
Hey,

Great tool.  Got a first CAP project up and running on PostgreSQL Hyperscaler in no time.

When I tried converting a second project from HANA I am getting the follow error though:

`error: syntax error at or near "user"`

![dbm-pg-issue-1](https://user-images.githubusercontent.com/14307554/162175546-5a6ccc74-57ef-4a63-a1a6-b68966a87263.jpg)

Error code '42601' seems to be a SQL syntax error.

I did a search on the user keyword within our cds files but couldn't find anything really spectaculair or uncommon. 
A normal CDS build works fine and creates the gen content ( although I am not sure this is related ofc ).

Is there any way to get a better idea on why this is happening ?

Thanks,

Steven

**Comment by gregorwolf** [comment]
Hi @sedacrivity,

can you please provide more details when exactly your get this error.

Have you tried if setting `DEBUG=cds-pg` provides further details?

CU
Gregor

**Comment by sedacrivity** [comment]
@gregorwolf  Thanks for your quick response.

I am simply executing 

`npx cds-dbm deploy`

in the cli. Using a local DB.

The DEBUG flag does not give any more info.

**Comment by sedacrivity** [comment]
Ok found the issue thanks to the log in the actual postgresql instance.

I have a table with a field 

user: VARCHAR(255)

But 'user' turns out to be a reserved keyword in Postgresql.   
https://www.postgresql.org/docs/current/sql-keywords-appendix.html

Might be an idea to scan for those and give a warning ?
