### ISSUE TITLE
"bash: ./deploy.sh: Permission denied (STDERR, APP/TASK/deploy_to_postgresql)" while deploying to cloud foundry

### ISSUE THREAD

**Issue by alamjewel** [mikezaschka/cds-dbm#214]
Facing error while deploying to cloud foundry.

package.json
"dependencies": {
    "@sap/cds": "^5",
    "cds-dbm": "^0.0.36",
    "cds-pg": "^0.1.29",
    "express": "^4"
  },
"cds": {
    "build": {
      "tasks": [
        {
          "for": "node-cf",
          "src": "srv",
          "options": {
            "model": [
              "db",
              "srv",
              "app"
            ]
          }
        },
        {
          "use": "cds-dbm/dist/build/postgres-cf",
          "for": "postgres-cf",
          "src": "db",
          "options": {
            "deployCmd": "npx cds-dbm deploy --load-via delta --auto-undeploy"
          }
        }
      ]
    },
    "requires": {
      "db": {
        "kind": "database"
      },
      "database": {
        "dialect": "plain",
        "impl": "cds-pg",
        "model": [
          "srv"
        ],
        "credentials": {
          "host": "...",
          "port": 4136,
          "database": "...",
          "user": "...",
          "password": "..."
        }
      }
    },
    "migrations": {
      "db": {
        "schema": {
          "default": "public",
          "clone": "_cdsdbm_clone",
          "reference": "_cdsdbm_ref"
        },
        "deploy": {
          "tmpFile": "tmp/_autodeploy.json",
          "undeployFile": "db/undeploy.json"
        }
      }
    }
  }

**Comment by alamjewel** [comment]
Thanks @gregorwolf.
No, I use the 'cap-devtoberfest' project. By the way, by the grace of almighty Allah, I fix the issue.

**Comment by gregorwolf** [comment]
Would be good if you can share your fix to help others.

**Comment by alamjewel** [comment]
Extremely Sorry for late reply.
Just adding the `chmod 777 -R deploy.sh && ./deploy.sh`.
If almighty Allah want's, i think this will work.
Thanks a lot.

**Comment by gregorwolf** [comment]
Would say:

`chmod 755 -R deploy.sh && ./deploy.sh`

should be enough to keep authorizations as restrictive as possible.

**Comment by alamjewel** [comment]
Thanks a lot.
