### ISSUE TITLE
Support to CDS 6.5.0 and cds-pg 0.1.35

### ISSUE THREAD

**Issue by ryegrosT8** [mikezaschka/cds-dbm#292]
Hi there.

I recently submitted a pull request on cds-pg project to update the support of @sap/cds to version 6.5.0 (https://github.com/sapmentors/cds-pg/pull/383).

After looking on cds-dbm project, I founded some minor changes that can be done to also support @sap/cds 6.5.0 and the new version of cds-pg.

I submitted those changes at pull request (https://github.com/mikezaschka/cds-dbm/pull/291). Could you guys please evaluate if it's acceptable?

Best Regards,
Rafael Yegros.

**Comment by mikezaschka** [comment]
Merged and closed.
Thanks a lot for the contribution!
