### ISSUE TITLE
Cannot find module 'date-format'

### ISSUE THREAD

**Issue by ryegrosT8** [mikezaschka/cds-dbm#293]
Hi @mikezaschka.

I was not sure if I should open a new issue or add a comment on the closed Pull Request (https://github.com/mikezaschka/cds-dbm/issues/292). 

Choose to open a new Issue and describe an workaround in case of the fix takes some time.

The problem: 

After upgrade to version 0.1.0, I got the following error

```
$ npx cds-dbm deploy --load-via delta --auto-undeploy
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'date-format'
Require stack:
- project/node_modules/cds-dbm/dist/ChangelogGenerator.js
- project/node_modules/cds-dbm/dist/cli/generate.js
- project/node_modules/yargs/index.cjs
- project/node_modules/cds-dbm/dist/cli.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (project/node_modules/cds-dbm/dist/ChangelogGenerator.js:10:39)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'project/node_modules/cds-dbm/dist/ChangelogGenerator.js',
    'project/node_modules/cds-dbm/dist/cli/generate.js',
    'project/node_modules/yargs/index.cjs',
    'project/node_modules/cds-dbm/dist/cli.js'
  ]
}
```
When I was running tests for the PR that helped to create this new version (https://github.com/mikezaschka/cds-dbm/pull/291), the class ChangelogGenerator was not exists in my dist folder:

The Dist folder generated for PR https://github.com/mikezaschka/cds-dbm/pull/291.

![image](https://user-images.githubusercontent.com/120337840/218821184-0f9cbfdb-12bb-44d6-aaac-2e82d6ac0d51.png)

The published version on npm seems quite different:
![image](https://user-images.githubusercontent.com/120337840/218821539-fbccfc94-b3c0-4987-9e0c-7122d7a7d3c7.png)
![image](https://user-images.githubusercontent.com/120337840/218821604-f26415d1-2ad9-4dd4-a4d6-54ed8fe1f0b3.png)

I wondering if something goes wrong when publishing the package at npm.org. Could you check please? Maybe missing “npm run build” script automation?

Workaround:
1 - Go to node_modules/cds-dbm folder and run:
```
npm i
npm run build
```

2 - Instead of run the cli cds-dbm command-line, goes to root folder of your app and use :
```
node node_modules/cds-dbm/dist/cli.js deploy  --load-via delta --auto-undeploy
``` 

Best Regards.
Rafael Yegros.

**Comment by mikezaschka** [comment]
My bad. I did a local build and did not clean up the `dist` folder correctly, so I was having development fragments from another branch lying around.
I will clean up the mess and publish a new version within the next hours.

**Comment by mikezaschka** [comment]
Done: https://www.npmjs.com/package/cds-dbm/v/0.1.1

**Comment by ryegrosT8** [comment]
Thank you very much, it is working as expected now. Closing this issue.
