### ISSUE TITLE
cflinuxsf4 not supported as stack for nodejs_buildpack?

### ISSUE THREAD

**Issue by mhay-at-dvelop** [mikezaschka/cds-dbm#334]
Hi community,
I changed the stack for our cap-service to cflinuxsf4 because sap has deprecated cflinuxsf3. Changing the stack for our cap-service worked without problems. But using the database-deployer throws the error, that the stack is not supported. 
Here is my entry in our mta.yaml for the multitarget-application.

![image](https://user-images.githubusercontent.com/103051901/228577339-ec7a2352-1595-4b15-8f38-75c0fdf4ca9d.png)

Any ideas? 
Kind regards
Matthias

**Comment by gregorwolf** [comment]
I would suggest you try with the latest version of the [apt-buildpack](https://github.com/cloudfoundry/apt-buildpack). The PR [tests: temporarily install fs4 compatible static/binary BPs #123](https://github.com/cloudfoundry/apt-buildpack/pull/123) was merged 14 days ago.

**Comment by SVLaursen** [comment]
Recently ran into this issue as well during a deployment. 

All that is needed for now to get you running at least is to make the following change to your buildpacks:

```yaml
...
parameters:
      buildpacks: [https://github.com/cloudfoundry/apt-buildpack#v0.3.0, nodejs_buildpack]
....
```

This is only a temporary fix, but it will get you running for now.

**Comment by mhay-at-dvelop** [comment]
Hi together,

worked for me to go to apt-buildpack 0.3.0.
Thx to Gregor and Simon :-)
