### ISSUE TITLE
Using 0.0.12 results in database "981c1fe2f6fa" does not exist

### ISSUE THREAD

**Issue by gregorwolf** [mikezaschka/cds-dbm#4]
Hi Mike,

I've tried the 0.0.12 version in the [pg-beeshop](https://github.com/gregorwolf/pg-beershop/) with the deploy to SAP CP with the PostgreSQL Hyperscaler. The following credentials are provided:

```
  "credentials": {
    "username": "981c1fe2f6fa",
    "dbname": "OQypNRRXsOKZ",
```

unfurtunately that currently results in this error:

```
error: database "981c1fe2f6fa" does not exist
    at Parser.parseErrorMessage (/home/vcap/deps/0/node_modules/cds-dbm/node_modules/pg-protocol/dist/parser.js:278:15)
    at Parser.handlePacket (/home/vcap/deps/0/node_modules/cds-dbm/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/vcap/deps/0/node_modules/cds-dbm/node_modules/pg-protocol/dist/parser.js:39:38)
    at TLSSocket.<anonymous> (/home/vcap/deps/0/node_modules/cds-dbm/node_modules/pg-protocol/dist/index.js:10:42)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at TLSSocket.Readable.push (_stream_readable.js:212:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23) {
  length: 97,
  severity: 'FATAL',
  code: '3D000',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'postinit.c',
  line: '880',
  routine: 'InitPostgres'
}
```

Looks like your change to detect if the database exists takes the username instead of the dbname.

When reverting back to 0.0.11 everything is fine and I've made the [Node.JS deployer working again](https://github.com/gregorwolf/pg-beershop/commit/40f4e97140bb7ea7fb61edcda4b764e361c551d1).

Best regards
Gregor

**Comment by mikezaschka** [comment]
Just released version 0.0.13, which should use the correct property (dbname -> database).

**Comment by gregorwolf** [comment]
Unfortunately still the same error:

`error: database "8b0ab946e93f" does not exist`

with this environment:

```
  "credentials": {
    "username": "8b0ab946e93f",
    "dbname": "OQypNRRXsOKZ",
```

**Comment by mikezaschka** [comment]
It does work on the local docker PostgreSQL.
I'm going to checkout your deployer module and try to analyze, what's wrong here.

**Comment by mikezaschka** [comment]
Update in version 0.0.14:
The deploy task does not try to create the database by default anymore. This specifically needs to be specified:

`npx cds-dbm deploy --create-db`

This should fix your issue, but I will also look into the real problem, why the username is being used instead of the database name when deploying to SCP.
Thus, keeping this open.

**Comment by gregorwolf** [comment]
Think that is fixed too.
